[2022-12-11 14:32:03,473] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.sum_column_task scheduled__2022-12-11T14:31:00+00:00 [queued]>
[2022-12-11 14:32:03,489] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.sum_column_task scheduled__2022-12-11T14:31:00+00:00 [queued]>
[2022-12-11 14:32:03,491] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:32:03,492] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 14:32:03,493] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:32:03,513] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): sum_column_task> on 2022-12-11 14:31:00+00:00
[2022-12-11 14:32:03,517] {standard_task_runner.py:52} INFO - Started process 837 to run task
[2022-12-11 14:32:03,525] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'sum_column_task', 'scheduled__2022-12-11T14:31:00+00:00', '--job-id', '481', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmp090p9_d4', '--error-file', '/tmp/tmpz4_sldvl']
[2022-12-11 14:32:03,526] {standard_task_runner.py:80} INFO - Job 481: Subtask sum_column_task
[2022-12-11 14:32:03,627] {task_command.py:369} INFO - Running <TaskInstance: first_dag.sum_column_task scheduled__2022-12-11T14:31:00+00:00 [running]> on host 7e39590a7807
[2022-12-11 14:32:03,733] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=sum_column_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T14:31:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T14:31:00+00:00
[2022-12-11 14:32:03,751] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first-dag.py", line 31, in sum_column_and_diff
    sum_columns = reduce(lambda a, b: (a[0] + b[0], a[1] + b[1]), prepare_lines)
  File "/opt/airflow/dags/first-dag.py", line 29, in <lambda>
    (int(x[0]), int(x[1].replace("\n", ""))),
ValueError: invalid literal for int() with base 10: 'None779'
[2022-12-11 14:32:03,765] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_dag, task_id=sum_column_task, execution_date=20221211T143100, start_date=20221211T143203, end_date=20221211T143203
[2022-12-11 14:32:03,779] {standard_task_runner.py:97} ERROR - Failed to execute job 481 for task sum_column_task (invalid literal for int() with base 10: 'None779'; 837)
[2022-12-11 14:32:03,820] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-11 14:32:03,869] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-11 14:32:50,499] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.sum_column_task scheduled__2022-12-11T14:31:00+00:00 [queued]>
[2022-12-11 14:32:50,532] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.sum_column_task scheduled__2022-12-11T14:31:00+00:00 [queued]>
[2022-12-11 14:32:50,533] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:32:50,535] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 14:32:50,537] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 14:32:50,573] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): sum_column_task> on 2022-12-11 14:31:00+00:00
[2022-12-11 14:32:50,587] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'sum_column_task', 'scheduled__2022-12-11T14:31:00+00:00', '--job-id', '491', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpmm_edm5m', '--error-file', '/tmp/tmpc8s459up']
[2022-12-11 14:32:50,579] {standard_task_runner.py:52} INFO - Started process 870 to run task
[2022-12-11 14:32:50,610] {standard_task_runner.py:80} INFO - Job 491: Subtask sum_column_task
[2022-12-11 14:32:50,718] {task_command.py:369} INFO - Running <TaskInstance: first_dag.sum_column_task scheduled__2022-12-11T14:31:00+00:00 [running]> on host 7e39590a7807
[2022-12-11 14:32:50,861] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=sum_column_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T14:31:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T14:31:00+00:00
[2022-12-11 14:32:50,883] {python.py:173} INFO - Done. Returned value was: -532
[2022-12-11 14:32:50,939] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=sum_column_task, execution_date=20221211T143100, start_date=20221211T143250, end_date=20221211T143250
[2022-12-11 14:32:50,996] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 14:32:51,046] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
