[2022-12-11 15:00:03,312] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:50:00+00:00 [queued]>
[2022-12-11 15:00:03,327] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:50:00+00:00 [queued]>
[2022-12-11 15:00:03,328] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 15:00:03,329] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 15:00:03,331] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 15:00:03,351] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate_two_int_task> on 2022-12-11 14:50:00+00:00
[2022-12-11 15:00:03,356] {standard_task_runner.py:52} INFO - Started process 1690 to run task
[2022-12-11 15:00:03,360] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'generate_two_int_task', 'scheduled__2022-12-11T14:50:00+00:00', '--job-id', '669', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmp8x2zr6l7', '--error-file', '/tmp/tmppxmbw7ys']
[2022-12-11 15:00:03,362] {standard_task_runner.py:80} INFO - Job 669: Subtask generate_two_int_task
[2022-12-11 15:00:03,456] {task_command.py:369} INFO - Running <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-11T14:50:00+00:00 [running]> on host 7e39590a7807
[2022-12-11 15:00:03,564] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=generate_two_int_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T14:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T14:50:00+00:00
[2022-12-11 15:00:03,581] {python.py:173} INFO - Done. Returned value was: None
[2022-12-11 15:00:03,602] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=generate_two_int_task, execution_date=20221211T145000, start_date=20221211T150003, end_date=20221211T150003
[2022-12-11 15:00:03,633] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 15:00:03,685] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
