[2022-12-11 17:43:04,265] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.wait_for_file scheduled__2022-12-11T17:31:00+00:00 [queued]>
[2022-12-11 17:43:04,333] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.wait_for_file scheduled__2022-12-11T17:31:00+00:00 [queued]>
[2022-12-11 17:43:04,339] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 17:43:04,340] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 17:43:04,353] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 17:43:04,583] {taskinstance.py:1377} INFO - Executing <Task(PythonSensor): wait_for_file> on 2022-12-11 17:31:00+00:00
[2022-12-11 17:43:04,620] {standard_task_runner.py:52} INFO - Started process 3890 to run task
[2022-12-11 17:43:04,788] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'wait_for_file', 'scheduled__2022-12-11T17:31:00+00:00', '--job-id', '1123', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmp6k7vzyj1', '--error-file', '/tmp/tmpxm_yvt1d']
[2022-12-11 17:43:04,859] {standard_task_runner.py:80} INFO - Job 1123: Subtask wait_for_file
[2022-12-11 17:43:05,112] {task_command.py:369} INFO - Running <TaskInstance: first_dag.wait_for_file scheduled__2022-12-11T17:31:00+00:00 [running]> on host 7e39590a7807
[2022-12-11 17:43:06,200] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=wait_for_file
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T17:31:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T17:31:00+00:00
[2022-12-11 17:43:06,203] {python.py:66} INFO - Poking callable: <function _wait_for_file at 0x7f6cec9c0cb0>
[2022-12-11 17:43:06,505] {logging_mixin.py:115} INFO - _wait_for_file True
[2022-12-11 17:43:06,508] {logging_mixin.py:115} INFO - total attempt 0
[2022-12-11 17:44:06,579] {python.py:66} INFO - Poking callable: <function _wait_for_file at 0x7f6cec9c0cb0>
[2022-12-11 17:44:10,502] {logging_mixin.py:115} INFO - _wait_for_file True
[2022-12-11 17:44:10,516] {logging_mixin.py:115} INFO - total attempt 0
[2022-12-11 17:45:10,547] {python.py:66} INFO - Poking callable: <function _wait_for_file at 0x7f6cec9c0cb0>
[2022-12-11 17:45:11,621] {logging_mixin.py:115} INFO - _wait_for_file True
[2022-12-11 17:45:11,632] {logging_mixin.py:115} INFO - total attempt 0
[2022-12-11 17:50:56,274] {python.py:66} INFO - Poking callable: <function _wait_for_file at 0x7f6cec9c0cb0>
[2022-12-11 17:51:04,412] {logging_mixin.py:115} INFO - _wait_for_file True
[2022-12-11 17:51:04,416] {logging_mixin.py:115} INFO - total attempt 0
[2022-12-11 17:51:47,206] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-12-11 17:51:47,320] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3890. PIDs of all processes in the group: [3890]
[2022-12-11 17:51:47,326] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3890
[2022-12-11 17:51:47,337] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-11 17:51:48,374] {process_utils.py:75} INFO - Process psutil.Process(pid=3890, status='terminated', exitcode=0, started='17:43:04') (3890) terminated with exit code 0
